CREATE TABLE `apt_model` (
  `ID` varchar(6) NOT NULL,
  `NO_OF_BEDROOMS` int(11) DEFAULT NULL,
  `NO_OF_BATHROOMS` int(11) DEFAULT NULL,
  `RENT_RANGE` varchar(20) DEFAULT NULL,
  `AREA` varchar(11) DEFAULT NULL COMMENT 'In Square Feet',
  `SECURITY_DEPOSITE` varchar(20) DEFAULT NULL,
  `MAX_OCCUPANCY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
